[pytest]
testpaths = tests
python_files = test_*.py *_test.py
python_functions = test_*

markers =
    ui: UI тесты
    api: API тесты
    sql: SQL тесты
    smoke: Дымовые тесты для быстрой проверки
    regression: Полные регрессионные тесты
    positive: Позитивные сценарии
    negative: Негативные сценарии
    slow: Медленные тесты
    flaky: Нестабильные тесты
